name: pull_workflow
on:
  pull_request_review:
    types: [submitted]
  pull_request_target:
    types: [synchronize,opened,closed,review_requested]   

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.SECR }}
          script: |
            const script = require('./\.github/workflows/scripts/pull_workflow.js')
            script({github, context})
